version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: "mysql:8.0"
    restart: always 
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: testdatabase
      MYSQL_ROOT_PASSWORD: root